# Generated by Django 2.0.7 on 2018-07-25 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webname', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Topic'),
        ),
    ]
